name: librepaint3d
description: FOSS Paint 3D
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  image: ^4.5.2
  dcanvas:
    path: ../dcanvas
  drawlite:
    path: ../drawlite/dart

dev_dependencies:
  hotreloader: ^4.3.0
  lints: ^4.0.0
  test: ^1.24.0
